language: python
sudo: required
services:
 - docker

script:
 - docker build -t gh0stik/app -f Dockerfile.dev .

deploy:
 provider: elasticbeanstalk
 region: "eu-central-1"
 app: "docker-test-app"
 env: "DockerTestApp-env"
 bucket_name: "elasticbeanstalk-eu-central-1-544397098000"
 bucket_path: "docker-test-app"
 on:
  branch: main
 access_key_id:
  secure: "$AWS_ACCESS_KEY"
 secret_access_key: 
  secure: "$AWS_SECRET_KEY"
