language: python
sudo: required
services:
 - docker

before_install:
 - docker build -t gh0stik/app -f Dockerfile.dev .

install:
 - pip3 install -r requirements.txt

deploy:
 provider: elasticbeanstalk
 region: "eu-central-1"
 app: "docker-test-app"
 env: "DockerTestApp-env"
 bucket_name: "elasticbeanstalk-eu-central-1-544397098000"
 bucket_path: "docker-test-app"
 on:
  branch: main
 access_key_id: $access_key_id
 secret_access_key: 
  secure: "$secret_access_key"
