sudo: required
services:
 - docker

language: python
python:
 - "3.8"
before_install:
 - docker-compose build

install:
 - pip3 install -r requirements.txt

deploy:
 provider: elasticbeanstalk
 region: "eu-central-1"
 app: "docker-test-app"
 env: "DockerTestApp-env"
 bucket_name: "elasticbeanstalk-eu-central-1-544397098000"
 bucket_path: "docker-test-app"
 on:
  branch: main
 access_key_id: $access_key_id
 secret_access_key: 
  secure: "$secret_access_key"
