version: '3'
services:
 app:
  image: gh0stik:app
  build:
   context: .
   dockerfile: Dockerfile.dev
  ports:
   - "80:5000"
  volumes:
   - ./templates:/var/www/html/templates 
 tests:
  image: gh0stik:test
  build:
   context: .
   dockerfile: Dockerfile.dev
  volumes:
   - ./templates:/var/www/html/templates
  command: ["python3", "-m", "unittest", "test_app.py"]
